import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import { Providers } from '@/components/providers';

import { Space_Mono } from 'next/font/google';

import { Bricolage_Grotesque } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import { IconHome } from '@tabler/icons-react';

import { FloatingNav } from '@/components/ui/floating-navbar';
const fontHeading = Bricolage_Grotesque({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-heading',
});
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
const fontBody = Space_Mono({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-body',
	weight: ['400', '700'],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const navItems = [
		{
			name: 'Home',
			link: '/',
			icon: <IconHome className='h-4 w-4 text-neutral-500 dark:text-white' />,
		},
		{
			name: 'Dashboard',
			link: '/dashboard',
			icon: <IconHome className='h-4 w-4 text-neutral-500 dark:text-white' />,
		},
	];
	return (
		<html lang='en'>
			<body
				className={cn('antialiased', fontHeading.variable, fontBody.variable)}
			>
				<Providers
					attribute='class'
					defaultTheme='system'
					enableSystem={true}
					disableTransitionOnChange
				>
					<FloatingNav navItems={navItems} />
					{children}
					<Toaster />
				</Providers>
			</body>
		</html>
	);
}
